### ISSUE TITLE
Pashword

### ISSUE THREAD

**Issue by poudenes** [Peppershade/pashword-docker#1]
Hi There,

I see last update of Pashword was on 22 august. There are some new updates on the official GitHub.
When will you update yours? Im using yours because of docker installation possibility :)

Cheers,
Peter

**Comment by Peppershade** [comment]
Hi,

Didn't notice it yet, so good that you create the issue. I'll update my container today.

**Comment by poudenes** [comment]
Keep up the good work!

I did a request to the dev to make it possible to enter in URL: <ip>:<port> or <url>:<port>
Sometimes I want a specific IP with port. I use some applications on my NAS in docker and they all have other ports.
He implement his so that's why I asked you to update haha :)

**Comment by Peppershade** [comment]
Docker image is updated on `peppershade/pashword:dev`

Give it a try :)

**Comment by poudenes** [comment]
Updated and working. Thanks for the FAST actions!
